"""
Django settings for ku_djangoo project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PUBLIC_DATASET_ROOT = os.path.join(BASE_DIR, 'asset/user/dataset/public/')
PUBLIC_DATASET_DIR = '/public/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-...'
MINIO_ACCESS_KEY = "..."
MINIO_SECRET_KEY = "..."
MINIO_BUCKET1_ADDR = "..."

MINIO_API_ADDRESSES = [
    "http://0.0.0.0:0000",
    "http://0.0.0.0:0000",
    "http://0.0.0.0:0000",
    "http://0.0.0.0:0000"
]

MINIO_API_ADDR = "0.0.0.0:0000"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_REDIRECT_URL = '/polls/login-view'

# API REST definition

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Default permissions
    ),
}

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'Content-Disposition',
    'content-type',
    'Connection',
]

CORS_EXPOSE_HEADERS = [
    'Content-Disposition', 
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3002",
    "http://localhost:3002",
]
CSRF_COOKIE_DOMAIN = '127.0.0.1'
CSRF_COOKIE_NAME = 'csrf_token'
CSRF_COOKIE_PATH = "/"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
CSRF_USE_SESSIONS = True
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',
    'https://localhost:8000',
    'http://localhost:8000',
    "http://localhost:3002",
]
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'Lax'

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

SESSION_COOKIE_AGE = 43200  # 60×60×1 = 1 hour 

# Enable these three only when using HTTPS
SECURE_SSL_REDIRECT = False
# Enable these two below only when accessing admin website
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    "corsheaders",
    "django.contrib.postgres",
    'django.contrib.humanize',
    "polls.apps.PollsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ku_djangoo.urls' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ku_djangoo.wsgi.application'

DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400000 # 25 GB

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'template1', 
        'USER': 'postgres',
        'PASSWORD': 'ku202425',
        'HOST': '0.0.0.0',      # 127.0.0.1 # 0.0.0.0 # 192.168.122.1
        'PORT': '5432',                 # 24
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT_DATASET = os.path.join(BASE_DIR, 'dataset')
STATIC_ROOT_MODEL = os.path.join(BASE_DIR, 'model')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
