"""
Django settings for ku_djangoo project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from os import getenv, path
import dotenv
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_file = BASE_DIR / '.env.local'

if path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)


ASSET_DIR = getenv("ASSET_DIR")
ROOT_DATASET_DIR = getenv("ROOT_DATASET_DIR")
ROOT_MODEL_DIR = getenv("ROOT_MODEL_DIR")
ROOT_TEMP = getenv("ROOT_TEMP")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("DJANGO_SECRET_KEY", get_random_secret_key())
MINIO_ACCESS_KEY = getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = getenv("MINIO_SECRET_KEY")
MINIO_BUCKET1_ADDR = getenv("MINIO_BUCKET1_ADDR")

MINIO_API_ADDRESSES = getenv("MINIO_API_ADDRESSES").split(',')

MINIO_API_ADDR = getenv("MINIO_API_ADDR")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv('DEBUG', 'False') == True

ALLOWED_HOSTS = getenv('DJANGO_ALLOWED_HOSTS').split(',')

LOGIN_REDIRECT_URL = '/polls/login-view'

# API REST definition

CORS_ALLOW_CREDENTIALS = True 

CORS_ALLOW_HEADERS = [
    'Content-Disposition',
    'content-type',
    'Connection',
    'x-csrftoken',
    'X-CSRFToken',
    'authorization',
    'mode',
]

CORS_EXPOSE_HEADERS = [
    'Content-Disposition', 
]

CORS_ALLOWED_ORIGINS = getenv('CORS_ALLOWED_ORIGINS').split(',')

CSRF_COOKIE_PATH = "/"
CSRF_TRUSTED_ORIGINS = getenv('CSRF_TRUSTED_ORIGINS').split(',')

SESSION_COOKIE_SAMESITE = 'Strict' # 'Strict' for production, same for CSRF_COOKIE_SAMESITE
CSRF_COOKIE_SAMESITE = 'Strict' 

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

SESSION_COOKIE_AGE = 43200  # 60×60×1 = 1 hour 

# Enable these three only when using HTTPS
SECURE_SSL_REDIRECT = False
# Enable these two below only when accessing admin website # Set both to False for development with HTTP
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = True

CSRF_USE_SESSIONS = False
# Choose either above or below but NOT both - CSRF is not set in the cookie but session_id is when Enabling both, causing issue.
CSRF_COOKIE_HTTPONLY = True

SESSION_COOKIE_HTTPONLY = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.postgres",
    'django.contrib.humanize',
    "polls.apps.PollsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    "corsheaders",
    "channels",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist"
]

# API REST definition

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ku_djangoo.urls' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ku_djangoo.wsgi.application'

DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400000 # 25 GB

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'template1', 
        'USER': getenv('POSTGRES_USER'),
        'PASSWORD': getenv('POSTGRES_PASSWORD'),
        'HOST': '0.0.0.0',      # 127.0.0.1 # 0.0.0.0 # 192.168.122.1
        'PORT': '5432',                 # 24
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static', 'dataset'),
    os.path.join(BASE_DIR, 'static', 'model'),    
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT_DATASET = os.path.join(BASE_DIR, 'static', 'dataset')
STATIC_ROOT_MODEL = os.path.join(BASE_DIR, 'static', 'model')

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
