# Generated by Django 4.2.11 on 2024-11-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_file_path_csv_dataset_dataset_directory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='file_path',
            new_name='model_directory',
        ),
    ]
