# Generated by Django 4.2.11 on 2024-10-22 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_login_net_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='login',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='a username', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='net_model',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='net_model',
            name='model_type',
            field=models.CharField(default='n/a', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='net_model',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='net_model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=320),
        ),
    ]
