# Generated by Django 5.1.2 on 2024-11-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_file_path_model_model_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='original_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.model'),
        ),
    ]
