# Generated by Django 5.1.2 on 2024-11-11 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_model_original_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.model')),
            ],
        ),
    ]
