# Generated by Django 4.2.11 on 2025-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_datasetactionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetactionset',
            name='action_type',
            field=models.IntegerField(choices=[('CLEANING', 1), ('ANALYSIS', 2), ('ENRICHMENT', 3), ('CURATION', 4), ('DATA_BALANCING', 5), ('EXPLAINABLE_AI', 6), ('__empty__', None)], default=None),
            preserve_default=False,
        ),
    ]
