# Generated by Django 4.2.11 on 2025-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_datasetactionset_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetactionset',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'CLEANING'), (2, 'ANALYSIS'), (3, 'ENRICHMENT'), (4, 'CURATION'), (5, 'DATA_BALANCING'), (6, 'EXPLAINABLE_AI'), (None, '__empty__')], unique=True),
        ),
    ]
