# Generated by Django 4.2.11 on 2025-02-10 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_datasetactionset_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelActionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(choices=[(1, 'ANALYSIS'), (2, 'DISTILLATION'), (3, 'FINE_TUNING'), (4, 'EXPLAINABLE_AI'), (None, '__empty__')], unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TaskAction',
            new_name='DatasetTaskAction',
        ),
        migrations.CreateModel(
            name='ModelTaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modelaction')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
        ),
        migrations.AddField(
            model_name='modelaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modelactionset'),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.model'),
        ),
    ]
