# Generated by Django 4.2.11 on 2025-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_modelaction_modelactionset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetactionset',
            name='action_type',
            field=models.CharField(choices=[('cleaning', 'CLEANING'), ('analysis', 'ANALYSIS'), ('enrichment', 'ENRICHMENT'), ('curation', 'CURATION'), ('balancing', 'BALANCING'), ('explainable_ai', 'EXPLAINABLE_AI')]),
        ),
    ]
