# Generated by Django 4.2.11 on 2025-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_datasetactionset_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetactionset',
            name='action_type',
            field=models.CharField(choices=[(None, '(Unknown)'), ('cleaning', 'CLEANING'), ('analysis', 'ANALYSIS'), ('enrichment', 'ENRICHMENT'), ('curation', 'CURATION'), ('balancing', 'BALANCING'), ('explainable_ai', 'EXPLAINABLE_AI')]),
        ),
        migrations.AlterField(
            model_name='modelactionset',
            name='action_type',
            field=models.CharField(choices=[(None, '(Unknown)'), ('analysis', 'ANALYSIS'), ('distillation', 'DISTILLATION'), ('fine_tuning', 'FINE_TUNING'), ('explainable_ai', 'EXPLAINABLE_AI')], unique=True),
        ),
    ]
